// Code generated by goctl. DO NOT EDIT.
package types

type Abstract struct {
	Docid   string `json:"docid"`
	Content string `json:"abstract"`
}

type ReqAbsId struct {
	Docid string `from:"docid"`
}

type ReqKeyWord struct {
	Key string `from:"key"`
}

type NlpTags struct {
	DocId         string `json:"docid"`
	SentenceIndex int    `json:"sentence_index"`
	SentenceText  string `json:"sentence_text"`
	Tokens        string `json:"tokens"`
	Lemmas        string `json:"lemmas"`
	PosTags       string `json:"pos_tags"`
	NerTags       string `json:"ner_tags"`
	DocOffsets    string `json:"doc_offsets"`
	DepTypes      string `json:"dep_types"`
	DepTokens     string `json:"dep_tokens"`
}

type CommonResp struct {
	Ok    bool   `json:"ok"`
	Error string `json:"error"`
}
