// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	mag "mag_service/api/internal/handler/mag"
	user "mag_service/api/internal/handler/user"
	"mag_service/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mag",
				Handler: mag.CreateDocumentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/mag",
				Handler: mag.UpdateDocumentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mag/id",
				Handler: mag.GetDocumentByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mag/search",
				Handler: mag.SearchDocumentByKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mag/nlp",
				Handler: mag.GetNlpByIdHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
