// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"es_service/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mag",
				Handler: CreateDocumentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/mag",
				Handler: UpdateDocumentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mag/id/:id",
				Handler: GetDocumentByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mag/search",
				Handler: SearchDocumentByKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mag/nlp",
				Handler: GetNlpByIdHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
